name: Publish to Github pages

on:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  github-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun run install:lib && bun install

      - name: Build demo
        run: bun run build:lib && bun run build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist/table/browser # The folder the action should deploy.