name: Publish Package to npm

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: ${{ github.event.repository.default_branch }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: npm ci

      # - name: Run tests
      #   run: npm test

      - name: Update package.json with release tag and commit
        run: |
          # Go to the library directory and update version
          cd projects/some-angular-utils/table

          TAG="${{ github.event.release.tag_name }}"
          echo "Updating package.json version to $TAG"
          npm version "$TAG" --no-git-tag-version

          # Go back to root and commit changes
          cd ../../..

          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add projects/some-angular-utils/table/package.json
          git commit -m "Update package.json to version $TAG"
          git push origin ${{ github.event.repository.default_branch }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: build package
        run: npm run build:lib

      - name: Publish to npm
        working-directory: dist/some-angular-utils/table
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}